// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouiastccdfhwxecpeioo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91aWFzdGNjZGZod3hlY3BlaW9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNjM4ODksImV4cCI6MjA2MDgzOTg4OX0.7ySKaZpBhm_tyuYgBxUHubq8xTPQRdkPbQ_cWLw-7DE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);